### ISSUE TITLE
For the error in channel.py

### ISSUE THREAD

**Issue by HandsomeManKris** [JungangGe/DRL_for_DDBC#3]
Dear Jungang:

In your init part,  
self.g = (np.random.randn(1, self.multi_paths) + np.random.randn(1, self.multi_paths) * 1j) / np.sqrt(2 * self.multi_paths)
 
and in the ir_change part, it is 
 e = (np.random.randn(1, self.multi_paths) + np.random.randn(1, self.multi_paths) * 1j) \
                * np.sqrt(1 - np.square(self.rho)) / np.sqrt(2)
it seems that you miss the self.multi_paths in the ir_change part, this problem greatly increase the strength of the channel you use, it should be 
e = (np.random.randn(1, self.multi_paths) + np.random.randn(1, self.multi_paths) * 1j) \
                * np.sqrt(1 - np.square(self.rho)) / np.sqrt(2 *self.multi_paths )
I am not sure whether this will influence all the results in your paper.(maybe the results should be lower in your paper)

you can check the norm value of self.g by using np.linalg.norm(self.g) in cascaded time slots and you can find that the strength increases a lot from slot 1 to slot 2.

Bests,

Kris

**Comment by JungangGe** [comment]
> Dear Jungang:
> 
> In your init part,
> self.g = (np.random.randn(1, self.multi_paths) + np.random.randn(1, self.multi_paths) * 1j) / np.sqrt(2 * self.multi_paths)
> 
> and in the ir_change part, it is
> e = (np.random.randn(1, self.multi_paths) + np.random.randn(1, self.multi_paths) * 1j)
> * np.sqrt(1 - np.square(self.rho)) / np.sqrt(2)
> it seems that you miss the self.multi_paths in the ir_change part, this problem greatly increase the strength of the channel you use, it should be
> e = (np.random.randn(1, self.multi_paths) + np.random.randn(1, self.multi_paths) * 1j)
> * np.sqrt(1 - np.square(self.rho)) / np.sqrt(2 *self.multi_paths )
> I am not sure whether this will influence all the results in your paper.(maybe the results should be lower in your paper)
> 
> you can check the norm value of self.g by using np.linalg.norm(self.g) in cascaded time slots and you can find that the strength increases a lot from slot 1 to slot 2.
> 
> Bests,
> 
> Kris

Dear Kris,

Thanks a lot for pointing this error. 

This error may not influence the results severely, I think. In the simulated scenarios, the received signal power is much larger than the power of the background noise. Thus, the intercell interference becomes the dominant factor that limits the network capacity. As you point out, the channel gains may increase a lot between two adjacent slots. It should be noted that the interference power also increases as the received desired signal power increases. As a consequence, the achievable rate will not be influenced a lot. On the other hand, the results of the other benchmark algorithms are obtained in the same channel conditions. Hence, I guess this error will not influence the results severely. 

Of course, I will re-run the simulation programs after I fix the error to check whether this will influence the results. 

Thanks again for pointing out this error.

Best regards,
Jungang
